# Generated by Django 5.1.1 on 2024-09-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='url_name',
        ),
    ]
