# Generated by Django 5.1.1 on 2024-10-18 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_task_url_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuningModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuning_id', models.UUIDField(unique=True)),
                ('tuning_model', models.CharField(max_length=64, verbose_name='调优模型')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('n_estimators', models.IntegerField()),
                ('criterion', models.CharField(max_length=64)),
                ('max_depth', models.IntegerField()),
                ('max_features', models.CharField(max_length=64)),
                ('random_state', models.IntegerField()),
                ('accuracy', models.FloatField(verbose_name='准确率')),
                ('precision', models.FloatField(verbose_name='精确率')),
                ('recall', models.FloatField(verbose_name='召回率')),
                ('result_model_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='模型路径')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuning_model_user', to='main.user')),
            ],
            options={
                'db_table': 'tuning_models',
            },
        ),
    ]
