# Generated by Django 5.1.1 on 2024-10-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tuningmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuningmodels',
            name='accuracy',
            field=models.FloatField(null=True, verbose_name='准确率'),
        ),
        migrations.AlterField(
            model_name='tuningmodels',
            name='precision',
            field=models.FloatField(null=True, verbose_name='精确率'),
        ),
        migrations.AlterField(
            model_name='tuningmodels',
            name='recall',
            field=models.FloatField(null=True, verbose_name='召回率'),
        ),
    ]
