# Generated by Django 5.1.1 on 2024-10-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_tuningmodels_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='exec_time',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
