# Generated by Django 5.1.1 on 2024-10-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_task_exec_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuningmodels',
            name='f1_score',
            field=models.FloatField(null=True, verbose_name='F1总分'),
        ),
    ]
