# Generated by Django 5.1.1 on 2024-10-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tuningmodels_f1_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuningmodels',
            name='exec_time',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
