# Generated by Django 5.1.1 on 2024-10-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tuningmodels_exec_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuningmodels',
            old_name='f1_score',
            new_name='f1_data',
        ),
    ]
