# Generated by Django 5.1.1 on 2025-01-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_f1_score_tuningmodels_f1_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuningmodels',
            name='n_neighbors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tuningmodels',
            name='p_measure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tuningmodels',
            name='weights',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tuningmodels',
            name='criterion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tuningmodels',
            name='max_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tuningmodels',
            name='max_features',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tuningmodels',
            name='n_estimators',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tuningmodels',
            name='random_state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
