# Generated by Django 5.1.1 on 2025-01-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tuningmodels_n_neighbors_tuningmodels_p_measure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddressRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, unique=True)),
                ('rule_type', models.CharField(choices=[('white', 'Whitelist'), ('black', 'Blacklist')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
